; Sound Effects for song Atlantis SFX, version 2.0, generated by Arkos Tracker 2.

AtlantisSFX_SoundEffects
AtlantisSFX_SoundEffectsDisarkGenerateExternalLabel

; The sound effects, starting at 1.
AtlantisSFX_SoundEffectsDisarkPointerRegionStart0
	dw AtlantisSFX_SoundEffects_Sound1	; Sound effect 1.
	dw AtlantisSFX_SoundEffects_Sound2	; Sound effect 2.
	dw AtlantisSFX_SoundEffects_Sound3	; Sound effect 3.
	dw AtlantisSFX_SoundEffects_Sound4	; Sound effect 4.
	dw AtlantisSFX_SoundEffects_Sound5	; Sound effect 5.
	dw AtlantisSFX_SoundEffects_Sound6	; Sound effect 6.
	dw 0	; Sound effect 7.
AtlantisSFX_SoundEffectsDisarkPointerRegionEnd0

AtlantisSFX_SoundEffectsDisarkByteRegionStart1
; Sound effect 1.
AtlantisSFX_SoundEffects_Sound1
	db 0	; Speed

	db 61	; Soft only. Volume: 15.
	dw 252	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 289	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 337	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 385	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 433	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 497	; Software period.

	db 173	; Soft only. Volume: 11.
	db 1	; Noise: 1.
	dw 577	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 657	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 737	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 833	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 929	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 1025	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 1121	; Software period.

	db 17	; Soft only. Volume: 4.
	dw 1217	; Software period.

AtlantisSFX_SoundEffects_Sound1_Loop	db 9	; Soft only. Volume: 2.
	dw 1361	; Software period.

	db 4	; End of the sound effect.

; Sound effect 2.
AtlantisSFX_SoundEffects_Sound2
	db 5	; Speed

AtlantisSFX_SoundEffects_Sound2_Loop	db 3	; Soft and Hard. Env: 8.
	dw 56	; Hardware period.
	dw 1795	; Software period.

	db 35	; Soft and Hard. Env: 12.
	dw 56	; Hardware period.
	dw 1795	; Software period.

	db 4	; End of the sound effect.

; Sound effect 3.
AtlantisSFX_SoundEffects_Sound3
	db 1	; Speed

AtlantisSFX_SoundEffects_Sound3_Loop	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 5078	; Software period.

	db 189	; Soft only. Volume: 15.
	db 8	; Noise: 8.
	dw 5380	; Software period.

	db 185	; Soft only. Volume: 14.
	db 2	; Noise: 2.
	dw 6778	; Software period.

	db 181	; Soft only. Volume: 13.
	db 16	; Noise: 16.
	dw 3591	; Software period.

	db 177	; Soft only. Volume: 12.
	db 2	; Noise: 2.
	dw 3804	; Software period.

	db 173	; Soft only. Volume: 11.
	db 2	; Noise: 2.
	dw 4030	; Software period.

	db 165	; Soft only. Volume: 9.
	db 16	; Noise: 16.
	dw 6039	; Software period.

	db 157	; Soft only. Volume: 7.
	db 31	; Noise: 31.
	dw 2015	; Software period.

	db 153	; Soft only. Volume: 6.
	db 7	; Noise: 7.
	dw 1345	; Software period.

	db 4	; End of the sound effect.

; Sound effect 4.
AtlantisSFX_SoundEffects_Sound4
	db 3	; Speed

AtlantisSFX_SoundEffects_Sound4_Loop	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 5078	; Software period.

	db 189	; Soft only. Volume: 15.
	db 8	; Noise: 8.
	dw 5380	; Software period.

	db 185	; Soft only. Volume: 14.
	db 2	; Noise: 2.
	dw 6778	; Software period.

	db 181	; Soft only. Volume: 13.
	db 16	; Noise: 16.
	dw 3591	; Software period.

	db 177	; Soft only. Volume: 12.
	db 2	; Noise: 2.
	dw 3804	; Software period.

	db 173	; Soft only. Volume: 11.
	db 2	; Noise: 2.
	dw 4030	; Software period.

	db 165	; Soft only. Volume: 9.
	db 16	; Noise: 16.
	dw 6039	; Software period.

	db 157	; Soft only. Volume: 7.
	db 31	; Noise: 31.
	dw 2015	; Software period.

	db 153	; Soft only. Volume: 6.
	db 7	; Noise: 7.
	dw 1345	; Software period.

	db 177	; Soft only. Volume: 12.
	db 2	; Noise: 2.
	dw 3804	; Software period.

	db 173	; Soft only. Volume: 11.
	db 2	; Noise: 2.
	dw 4030	; Software period.

	db 165	; Soft only. Volume: 9.
	db 16	; Noise: 16.
	dw 6039	; Software period.

	db 157	; Soft only. Volume: 7.
	db 31	; Noise: 31.
	dw 2015	; Software period.

	db 153	; Soft only. Volume: 6.
	db 7	; Noise: 7.
	dw 1345	; Software period.

	db 4	; End of the sound effect.

; Sound effect 5.
AtlantisSFX_SoundEffects_Sound5
	db 2	; Speed

AtlantisSFX_SoundEffects_Sound5_Loop	db 185	; Soft only. Volume: 14.
	db 7	; Noise: 7.
	dw 3389	; Software period.

	db 185	; Soft only. Volume: 14.
	db 16	; Noise: 16.
	dw 3389	; Software period.

	db 181	; Soft only. Volume: 13.
	db 3	; Noise: 3.
	dw 3389	; Software period.

	db 177	; Soft only. Volume: 12.
	db 15	; Noise: 15.
	dw 3389	; Software period.

	db 173	; Soft only. Volume: 11.
	db 12	; Noise: 12.
	dw 3389	; Software period.

	db 169	; Soft only. Volume: 10.
	db 9	; Noise: 9.
	dw 3389	; Software period.

	db 165	; Soft only. Volume: 9.
	db 6	; Noise: 6.
	dw 3389	; Software period.

	db 161	; Soft only. Volume: 8.
	db 4	; Noise: 4.
	dw 3389	; Software period.

	db 157	; Soft only. Volume: 7.
	db 1	; Noise: 1.
	dw 3389	; Software period.

	db 153	; Soft only. Volume: 6.
	db 21	; Noise: 21.
	dw 3389	; Software period.

	db 149	; Soft only. Volume: 5.
	db 9	; Noise: 9.
	dw 3389	; Software period.

	db 145	; Soft only. Volume: 4.
	db 17	; Noise: 17.
	dw 3389	; Software period.

	db 141	; Soft only. Volume: 3.
	db 5	; Noise: 5.
	dw 3389	; Software period.

	db 137	; Soft only. Volume: 2.
	db 9	; Noise: 9.
	dw 3389	; Software period.

	db 133	; Soft only. Volume: 1.
	db 17	; Noise: 17.
	dw 3389	; Software period.

	db 4	; End of the sound effect.

; Sound effect 6.
AtlantisSFX_SoundEffects_Sound6
	db 2	; Speed

	db 61	; Soft only. Volume: 15.
	dw 189	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 84	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 37	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 84	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 37	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 7	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 84	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 37	; Software period.

	db 29	; Soft only. Volume: 7.
	dw 7	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 84	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 37	; Software period.

	db 17	; Soft only. Volume: 4.
	dw 7	; Software period.

	db 13	; Soft only. Volume: 3.
	dw 84	; Software period.

	db 9	; Soft only. Volume: 2.
	dw 37	; Software period.

AtlantisSFX_SoundEffects_Sound6_Loop	db 5	; Soft only. Volume: 1.
	dw 7	; Software period.

	db 4	; End of the sound effect.

AtlantisSFX_SoundEffectsDisarkByteRegionEnd1
